sample_id model modification
LUMC-BioSemantics/phenopackets-rdf-schema pull request #8
Opened 2021-02-01 16:49 UTC by NuriaQueralt

hi @rajaram5 I modified sample_id model following the EJP IBM use case. I have added an RDF/TTL example, a PNG image and a ShEx file. Pls, could you review these model modifications and files? NB that I changed NCIT types to other OBO ontologies types like in IBM. tx!

2021-02-02 09:40 UTC, rajaram5 requested changes
Can you fix the rdf base url?

2021-02-02 09:40 UTC, rajaram5 commented on example-rdf/turtle/sample/sampleId.ttl
> +@prefix : <http://purl.org/ejp-rd/ibm/metadata/example-rdf/> .
@NuriaQueralt can you use phenopacket base url? Just to keep it genral

2021-02-08 21:57 UTC, NuriaQueralt commented
Hi @rajaram5 I have fixed the  RDF base URI from the ibm to phenopackets as you requested. Could be finished now the PR? tx!

2021-02-09 09:40 UTC, rajaram5 approved these changes

2021-02-09 09:40 UTC, rajaram5 commented
Looks good, can you please merger it?

2021-02-09 09:46 UTC, merged